const kitchen = {
  ru: {
    createOrder: "Создать заказ",
    myOrders: "Мои заказы",
    allProducts: "Все продукты",
    name: "Наименование",
    currentPrice: "Текущая цена",
    averagePrice: "Cредняя цена",
    quantity: "Текущее количество",
    amount: "Количество",
    units: "Единицы измерения",
    debit: "Списание",
    debitQuestion: "Количество для списания",
    title: "Наименование",
    sum: "Сумма",
    report: "Отчет",
    abbrUnits: "Ед. Изм.",
    total: "Итого:",
  },
  en: {
    createOrder: "Create order",
    myOrders: "My orders",
    allProducts: "All products",
    name: "Title",
    currentPrice: "Current price",
    averagePrice: "Average price",
    quantity: "Current quantity",
    amount: "Amount",
    units: "Units of measure",
    debit: "Debit",
    debitQuestion: "Amount to debit",
    title: "Title",
    sum: "Sum",
    report: "Report",
    abbrUnits: "Units",
    total: "Total:",
  },
  ua: {
    createOrder: "Створити замовлення",
    myOrders: "Мої замовлення",
    allProducts: "Всі продукти",
    name: "Назва",
    currentPrice: "Поточна ціна",
    averagePrice: "Середня ціна",
    quantity: "Наявна кількість",
    amount: "Кількість",
    units: "Одиниці виміру",
    debit: "Списання",
    debitQuestion: "Кількість для списання",
    title: "Назва",
    sum: "Сума",
    report: "Звіт",
    abbrUnits: "Од. вим.",
    total: "Всього:",
  },
  pl: {
    createOrder: "Stwórz zamówienie",
    myOrders: "Moje zamówienia",
    allProducts: "Wszystkie produkty",
    name: "Tytuł",
    currentPrice: "Aktualna cena",
    averagePrice: "Średnia cena",
    quantity: "Aktualna ilość",
    amount: "Ilość",
    units: "Jednostki",
    debit: "Spłata",
    debitQuestion: "Ilość do spłaty",
    title: "Tytuł",
    sum: "Suma",
    report: "Raport",
    abbrUnits: "Jed. Izm.",
    total: "Łącznie:",
  },
};

export default kitchen;
