const kitchen = {
  ru: {
    createOrder: "Создать заказ",
    myOrders: "Мои заказы",
    allProducts: "Все продукты",
    name: "Наименование",
    currentPrice: "Текущая цена",
    averagePrice: "Усредненная цена",
    quantity: "Текущее количество",
    amount: "Количество",
    units: "Единицы измерения",
    debit: "Списание",
    debitQuestion: "Количество для списания",
  },
  en: {
    createOrder: "Create order",
    myOrders: "My orders",
    allProducts: "All products",
    name: "Title",
    currentPrice: "Current price",
    averagePrice: "Average price",
    quantity: "Current quantity",
    amount: "Amount",
    units: "Units of measure",
    debit: "Debit",
    debitQuestion: "Amount to debit",
  },
  ua: {
    createOrder: "Створити замовлення",
    myOrders: "Мої замовлення",
    allProducts: "Всі продукти",
    name: "Назва",
    currentPrice: "Поточна ціна",
    averagePrice: "Середня ціна",
    quantity: "Наявна кількість",
    amount: "Кількість",
    units: "Одиниці виміру",
    debit: "Списання",
    debitQuestion: "Кількість для списання",
  },
  pl: {
    createOrder: "Stwórz zamówienie",
    myOrders: "Moje zamówienia",
    allProducts: "Wszystkie produkty",
    name: "Tytuł",
    currentPrice: "Aktualna cena",
    averagePrice: "Średnia cena",
    quantity: "Aktualna ilość",
    amount: "Ilość",
    units: "Jednostki",
    debit: "Spłata",
    debitQuestion: "Ilość do spłaty",
  },
};

export default kitchen;
