const main = {
  ru: {
    version: "Версия",
    scm: "Система управления снабжением предприятия",
    error: "Ошибка",
    loading: "Загрузка",
    ordered: "Заказано",
    done: "Выполнено",
    edit: "Редактировать",
    delete: "Удалить",
    confirmMessage: "Вы уверены?",
    confirm: "Подтвердить",
    cancel: "Отменить",
    editMessage: "Изменить",
    amountLabel: "Количество",
    priceLabel: "Общая цена",
    warning: "Внимание!",
    floatWarning: "Дроби в полях вводить через точку",
    dateOrdered: "Дата заказа",
    doneAmount: "выполнено",
  },
  en: {
    version: "Version",
    scm: "Supply management system",
    error: "Error",
    loading: "Loading",
    ordered: "Ordered",
    done: "Done",
    edit: "Edit",
    delete: "Delete",
    confirmMessage: "Are you sure?",
    confirm: "Confirm",
    cancel: "Cancel",
    editMessage: "Edit",
    amountLabel: "Amount",
    priceLabel: "Total price",
    warning: "Warning",
    floatWarning: "Fractions in the fields are set with a dot",
    dateOrdered: "Date ordered",
    doneAmount: "done",
  },
  ua: {
    version: "Версія",
    scm: "Система управління забезпеченням",
    error: "Помилка",
    loading: "Завантаження",
    ordered: "Замовлено",
    done: "Виконано",
    edit: "Редагувати",
    delete: "Видалити",
    confirmMessage: "Ви впевнені?",
    confirm: "Підтвердити",
    cancel: "Скасувати",
    editMessage: "Редагувати",
    amountLabel: "Кількість",
    priceLabel: "Загальна ціна",
    warning: "Попередження!",
    floatWarning: "Дроби в полях вводити через крапку",
    dateOrdered: "Дата замовлення",
    doneAmount: "виконано",
  },
  pl: {
    version: "Wersja",
    scm: "System zarządzania zasilaniem",
    error: "Błąd",
    loading: "Ładowanie",
    ordered: "Zamówione",
    done: "Wykonane",
    edit: "Edytuj",
    delete: "Usuń",
    confirmMessage: "Czy na pewno?",
    confirm: "Potwierdź",
    cancel: "Anuluj",
    editMessage: "Edytuj",
    amountLabel: "Ilość",
    priceLabel: "Cena całkowita",
    warning: "Ostrzeżenie!",
    floatWarning: "Ułamki wpisuje się w pola za pomocą kropki",
    dateOrdered: "Data zamówienia",
    doneAmount: "wykonane",
  },
};

export default main;
