const orderCombo = {
  ru: {
    chooseProduct: "Выберите продукт",
    amount: "Введите количество",
    order: "Заказать",
    add: "Добавить",
    newProduct: "Новый продукт",
    addDialogTitle: "Единицы измерения?",
    title: "Наименование",
    cancel: "Отмена",
    add: "Добавить",
  },
  en: {
    chooseProduct: "Choose product",
    amount: "Enter amount",
    order: "Order",
    add: "Add",
    newProduct: "New product",
    addDialogTitle: "Unit of measure?",
    title: "Product title",
    cancel: "Cancel",
    add: "Add",
  },
  ua: {
    chooseProduct: "Виберіть продукт",
    amount: "Введіть кількість",
    order: "Замовити",
    add: "Додати",
    newProduct: "Новий продукт",
    addDialogTitle: "Одиниці вимірювання?",
    title: "Назва",
    cancel: "Скасувати",
    add: "Додати",
  },
  pl: {
    chooseProduct: "Wybierz produkt",
    amount: "Wpisz ilość",
    order: "Zamów",
    add: "Dodaj",
    newProduct: "Nowy produkt",
    addDialogTitle: "Jednostka miary?",
    title: "Nazwa produktu",
    cancel: "Anuluj",
    add: "Dodaj",
  },
};

export default orderCombo;
